apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.0.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        x-small: &xsmall
          requests: { cpu: 50m, memory: 64Mi }
          limits:   { cpu: 100m, memory: 128Mi }
        
        small: &small
          requests: { cpu: 100m, memory: 128Mi }
          limits:   { cpu: 200m, memory: 256Mi }
        
        medium: &medium
          requests: { cpu: 150m, memory: 512Mi }
          limits:   { cpu: "1",  memory: 1Gi }
        
        medium: &large
          requests: { cpu: "200m", memory: 1Gi }
          limits:   { cpu: "1",  memory: 2Gi }
        
        prometheusOperator:
          resources: *small
          admissionWebhooks:
            enabled: false
          prometheusConfigReloader:
            resources: *xsmall
              
        prometheus:
          prometheusSpec:
            retention: 15d
            resources: *large
          configmapReload:
            resources: *xsmall
        
        alertmanager:  
          alertmanagerSpec:
            resources: *medium
          configmapReload:
            resources: *xsmall
        
        kube-state-metrics:
          resources: *small
        
        prometheus-node-exporter:
          resources: *xsmall
        
        grafana:
          resources: *small
          sidecar:
            dashboards:
              resources: *xsmall
            datasources:
              resources: *xsmall
        
        cleaner:
          resources: *xsmall
        create:
          resources: *xsmall

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
