apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: tunnel-system
data:
  config.yml: |
    tunnel: 0186a39a-4077-4831-866c-f98bdeb42147
    ingress:
      - service: http_status:404